name: ophub kernel 6.6.y

on:
  repository_dispatch:
  workflow_dispatch:
    inputs: { }

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          nproc
          uname -a
          cat /etc/*release
          free -h
          mount
          df -h
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Run build in Ubuntu 22.04 container
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          ls -alh
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ubuntu:22.04 \
            bash -c "
              chmod +x /workspace/build/kernel6.6-build-on-ubuntu22.04.sh ;
              /workspace/build/kernel6.6-build-on-ubuntu22.04.sh
            "

      - name: List build output
        run: |
          ls -alh  ${{ github.workspace }}/output/*
          md5sum ${{ github.workspace }}/output/*

      - name: Upload Image to Release
        uses: ncipollo/release-action@main
        with:
          tag: TB-RK3399ProD-kernel-6.6
          artifacts: ${{ github.workspace }}/output/*
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### ea_3588s镜像说明

            1. 镜像命名规则
            以 **TB-RK3399ProD_k6.6_${RELEASE}_${DESKTOP}_update.rar** 为例

            - "${RELEASE}" 发行版，可选一下几种发行版
              - bullseye - Debian 11
              - bookworm - Debian 12
              - trixie   - Debian 13
              - forky    - Debian 14
              - focal    - Ubuntu 20.04 LTS
              - jammy    - Ubuntu 22.04 LTS
              - noble    - Ubuntu 24.04 LTS
              - oracular - Ubuntu 24.10
              - plucky   - Ubuntu 25.04
              - resolute - Ubuntu 25.10
            - "${DESKTOP}" 桌面环境，可选 (mini,xfce,gnome)
            - 镜像类型，有两种类型
              - rockdev: RKDevTool + 分区镜像（uboot.img、boot.img、rootfs.img）
              - update : RKdevTool + update.img

            2. 系统密码

            - 用户名: root   密码: 1234
            - 用户名: admin  密码: admin
            - 用户名: teamhd 密码: teamhd
            - 用户名: linaro 密码: linaro

            3. rockdev构建输出(rockdev.rar)

            解压后打开RKDevTool.exe，选择'下载镜像'，点击'执行'即可

            ```
            RKDevTool/
            ├── bin
            │         ├── adb.exe
            │         ├── AdbWinApi.dll
            │         ├── AdbWinUsbApi.dll
            │         ├── AFPTool.exe
            │         └── RKImageMaker.exe
            ├── config.cfg
            ├── config.ini
            ├── Language
            │         ├── Chinese.ini
            │         └── English.ini
            ├── RKDevTool.exe
            └── rockdev
                └── image
                    ├── boot.img
                    ├── MiniLoaderAll.bin
                    ├── modules.tar.gz
                    ├── package-file
                    ├── parameter.txt
                    ├── rootfs.img
                    └── uboot.img
            ```

            4. update镜像构建输出(update.rar)

            解压后打开RKDevTool.exe，选择'升级固件'，点击'固件'，勾选镜像文件rockdev/img/update.img，点击'升级'即可

            ```
            RKDevTool/
            ├── bin
            │         ├── adb.exe
            │         ├── AdbWinApi.dll
            │         ├── AdbWinUsbApi.dll
            │         ├── AFPTool.exe
            │         └── RKImageMaker.exe
            ├── config.cfg
            ├── config.ini
            ├── Language
            │         ├── Chinese.ini
            │         └── English.ini
            ├── RKDevTool.exe
            └── rockdev
                └── image
                    └── update.img
            ```
